---
- name: Deploy lamp stack application
  hosts: all
  become: yes
  roles:
   - name: roles/common

- name: Deploy lamp stack application
  hosts: lamp-db
  become: yes
  roles:
   - name: roles/mysql

- name: Deploy lamp stack application
  hosts: lampweb
  become: yes
  roles:
   - name: roles/httpd-php
        
        
        
